### PR TITLE
Set correct fieldNumber in indexMetadata

### LINKED ISSUE #203: Fix primary key index definition error in update operation
The problem defining the index of a field with a primary key in function findSuitableIndex()
The problem is that fieldIndex = -1 in indexParts

```
`private static TarantoolIndexMetadata findSuitableIndex(TarantoolMetadataOperations operations,
                                                            TarantoolSpaceMetadata spaceMetadata,
                                                            Collection<TarantoolFieldMetadata> selectedFields) {
        Map<String, TarantoolIndexMetadata> allIndexes = operations.getSpaceIndexes(spaceMetadata.getSpaceName())
                .orElseThrow(() -> new TarantoolClientException(
                        "Metadata for space %s not found", spaceMetadata.getSpaceName()));

        TarantoolIndexMetadata suitableIndex = allIndexes.values().stream()
                .filter(metadata -> isSuitableIndex(metadata, selectedFields))
                .min(Comparator.comparingInt(m -> m.getIndexParts().size())) // Here
                .orElseThrow(() -> new TarantoolClientException("No indexes that fit the passed fields are found"));

        return suitableIndex;
    }`
```

### PR DESCRIPTION
**Pull request by dkasimovskiy**
There are two aspects of this issue:
1) Incorrect fieldNumber in the index part metadata. All fieldNumber decreased by one for all indexes.
2) When the driver try to find suitable index by field name it compares fieldNumber in the indexPartMetadata and selected fields. This can lead to a situation where the driver will select the wrong index or will not be able to find the index at all.

Closes #203

### CODE REVIEW

File: src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java [hunk 1]
```diff
@@ -286,6 +288,29 @@ public void clusterUpdateTest() throws ExecutionException, InterruptedException
...
+    public void test_clusterUpdate_shouldReturnTuple_ifSearchByFieldName() throws ExecutionException,
+            InterruptedException {
+        TarantoolSpaceOperations<TarantoolTuple, TarantoolResult<TarantoolTuple>> profileSpace =
+                client.space("cursor_test_space");
+
+        int itemId = 223;
+        List<Object> rowData = Arrays.asList(itemId, "Jane Doe", 10, null);
+        TarantoolTuple tarantoolTuple = tupleFactory.create(rowData);
+
+        TarantoolResult<TarantoolTuple> insertTuples = profileSpace.insert(tarantoolTuple).get();
```
Comment (vrogach2020) [inline src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java:301]: Use replace() instead of insert(). Also please add the space 'cursor_test_space' to truncateSpace() setup block to avoid intersections.

File: src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java [hunk 2]
```diff
@@ -233,7 +232,7 @@ private Map<String, TarantoolIndexMetadata> parseIndexes(Map<String, TarantoolFi
                         }
                         String fieldType = fieldTypeValue.asStringValue().asString();
 
-                        return new TarantoolIndexPartMetadataImpl(fieldNumber - 1, fieldType, fieldPath);
+                        return new TarantoolIndexPartMetadataImpl(fieldNumber, fieldType, fieldPath);
```
Comment (vrogach2020) [inline src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java:235]: Please add short description of the fix to changelog

**Review by vrogach2020 — CHANGES_REQUESTED** [review]

File: src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java (hunk 2 above)
Comment (dkasimovskiy) [reply src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java:235]: @ArtDu Nope. This is a bug. Possitions for indexes starts from 0.
Check with `box.space._vindex:select()`

**Review by vrogach2020 — APPROVED** [review]

File: src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java (hunk 2 above)
Comment (ArtDu) [reply src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java:235]: @dkasimovskiy I checked ) 
```lua
tarantool> box.space._vindex:select()[1]
---
- [272, 0, 'primary', 'tree', {'unique': true}, [[0, 'string']]]
...

tarantool> box.space._vindex:select()[1][1]
---
- 272
...

tarantool>
```
