### PR TITLE
Simplify code in connection selection strategies

### LINKED ISSUE #22: Flacky test RoundRobinStrategyTest.testSkipConnections
Sometimes this test fails with 
```
java.util.concurrent.CompletionException: org.opentest4j.AssertionFailedError: Unexpected exception thrown: io.tarantool.driver.exceptions.NoAvailableConnectionsException: No available connections

	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:325)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1809)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:1676)
Caused by: org.opentest4j.AssertionFailedError: Unexpected exception thrown: io.tarantool.driver.exceptions.NoAvailableConnectionsException: No available connections
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3005)
	at io.tarantool.driver.core.RoundRobinStrategyTest.lambda$testSkipConnections$9(RoundRobinStrategyTest.java:119)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1806)
	... 3 more
Caused by: io.tarantool.driver.exceptions.NoAvailableConnectionsException: No available connections
	at io.tarantool.driver.core.TarantoolConnectionSelectionStrategies$RoundRobinStrategy.next(TarantoolConnectionSelectionStrategies.java:57)
	at io.tarantool.driver.core.RoundRobinStrategyTest.lambda$testSkipConnections$8(RoundRobinStrategyTest.java:119)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 7 more
```
and sometimes it does pass.

`@RepeatedTest(value = 100)` does not help in reproducing - it seems that only first repetition can fail and all the others will always pass.

### PR DESCRIPTION
**Pull request by akudiyar**
Fixes #22

### CODE REVIEW

File: src/main/java/io/tarantool/driver/core/TarantoolConnectionSelectionStrategies.java [hunk 1]
```diff
@@ -37,28 +37,26 @@ public ConnectionSelectionStrategy create(TarantoolClientConfig config,
 
         private TarantoolConnectionIterator connectionIterator;
         private final int maxAttempts;
+        private final Collection<TarantoolConnection> connections;
```
Comment (isopov) [inline src/main/java/io/tarantool/driver/core/TarantoolConnectionSelectionStrategies.java:40]: This field seems to be unused.

File: src/main/java/io/tarantool/driver/core/TarantoolConnectionSelectionStrategies.java [hunk 2]
```diff
@@ -37,28 +37,26 @@ public ConnectionSelectionStrategy create(TarantoolClientConfig config,
 
         private TarantoolConnectionIterator connectionIterator;
```
Comment (isopov) [inline src/main/java/io/tarantool/driver/core/TarantoolConnectionSelectionStrategies.java:38]: Make this field final? (Since this class is ought to be used in multi-threaded environment)
