### PR TITLE
Prevent multiple call of TarantoolClusterDiscoveryConfig.Builder().withEndpoint()

### LINKED ISSUE #173: Discovery endpoint is overwritten when withEndpoint() called multiple times
See TarantoolClusterDiscoveryConfig.Builder#withEndpoint.
If this method is called twice it will overwrite previous endpoint setting. 
That leads to incorrect configuration that is not checked in runtime.

Now the it's impossible to specify more that 1 endpoint. 
We need to throw an exception or to support multiple endpoints in config.

### PR DESCRIPTION
**Pull request by dkasimovskiy**
Throw exception if TarantoolClusterDiscoveryConfig.Builder().withEndpoint() called multiple times
Closes #173

### CODE REVIEW

File: src/test/java/io/tarantool/driver/cluster/TarantoolClusterDiscoveryConfigTest.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+import org.junit.jupiter.api.Test;
+
+import static org.junit.jupiter.api.Assertions.*;
+
+/**
+ * @author Dmitry Kasimovskiy
+ */
+public class TarantoolClusterDiscoveryConfigTest {
+
+    private static class FakeTarantoolClusterDiscoveryEndpoint implements TarantoolClusterDiscoveryEndpoint {
```
Comment (wey1and) [inline src/test/java/io/tarantool/driver/cluster/TarantoolClusterDiscoveryConfigTest.java:13]: You can use empty class `new TarantoolClusterDiscoveryEndpoint(){}`, `BinaryClusterDiscoveryEndpoint` or `HTTPClusterDiscoveryEndpoint` instead.

Comment (wey1and) [inline src/test/java/io/tarantool/driver/cluster/TarantoolClusterDiscoveryConfigTest.java]: You can use empty class `new TarantoolClusterDiscoveryEndpoint(){}`, `BinaryClusterDiscoveryEndpoint` or `HTTPClusterDiscoveryEndpoint` instead.

**Review by wey1and — CHANGES_REQUESTED** [review]

File: src/test/java/io/tarantool/driver/cluster/TarantoolClusterDiscoveryConfigTest.java (hunk 1 above)
Comment (dkasimovskiy) [reply src/test/java/io/tarantool/driver/cluster/TarantoolClusterDiscoveryConfigTest.java]: Done

**Review by wey1and — APPROVED** [review]

**Review by wey1and — APPROVED** [review]

**Review by vrogach2020 — APPROVED** [review]
