### PR TITLE
Batch operation errors parsing

### LINKED ISSUE #334: Throw an exception if insertMany or ReplaceMany batch operations call returned any errors
These batch operations do not return exceptions in a normal "nil, error" format, but rather return "result, errors" that contains both results of the successful tuple inserts/replaces and errors for the unsuccessful ones. Although this approach is questionable, we have no other options now than to support this exotic return format.

I suggest throwing the first returned error because we can not do anything with the other errors rather than retrying the operation completely. Otherwise, the cluster will still be in an unknown inconsistent state.

### PR DESCRIPTION
**Pull request by akudiyar**
I decided to not make a separate `SingleValueCallResult` parser for batch operations specifically because I believe that the return format must be fixed in tarantool/crud and it will change in the future. So I added a new case to the common parser and refactored it a bit.

I haven't forgotten about:
- [x] Tests
- [x] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:
Fixes #334

### CODE REVIEW

File: src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java [hunk 1]
```diff
@@ -20,34 +23,41 @@
...
+        if (callResultSize == 0 || result.size() == 1 && resultValue.isNilValue()) {
             // [nil] or []
-            value = null;
-        } else if (result.size() == 2 && (result.get(0).isNilValue() && !result.get(1).isNilValue())) {
+            return null;
+        } else if (callResultSize == 2 && (resultValue.isNilValue() && !errorsValue.isNilValue())) {
             // [nil, "Error msg..."] or [nil, {str="Error msg...", stack="..."}]
-            throw TarantoolErrorsParser.parse(result.get(1));
+            throw TarantoolErrorsParser.parse(errorsValue);
+        } else if (callResultSize == 2 && errorsValue.isArrayValue()) {
```
Comment (ArtDu) [inline src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java:46]: nit: You don't need else for every conditional branch here because you return or throw in them

File: src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java [hunk 2]
```diff
@@ -20,34 +23,41 @@
...
+    }
+
+    private T parseResult(ArrayValue result, Function<Value, T> valueGetter) {
         if (result == null) {
             throw new TarantoolFunctionCallException("Function call result is null");
         }
-        if (result.size() == 0 || result.size() == 1 && result.get(0).isNilValue()) {
+        int callResultSize = result.size();
+        Value resultValue = result.getOrNilValue(0);
+        Value errorsValue = result.getOrNilValue(1);
```
Comment (ArtDu) [inline src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java:39]: Does it change anything? Below you use the same `isNilValue()`

File: src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java [hunk 3]
```diff
@@ -20,34 +23,41 @@
...
             // [nil] or []
-            value = null;
-        } else if (result.size() == 2 && (result.get(0).isNilValue() && !result.get(1).isNilValue())) {
+            return null;
+        } else if (callResultSize == 2 && (resultValue.isNilValue() && !errorsValue.isNilValue())) {
             // [nil, "Error msg..."] or [nil, {str="Error msg...", stack="..."}]
-            throw TarantoolErrorsParser.parse(result.get(1));
+            throw TarantoolErrorsParser.parse(errorsValue);
+        } else if (callResultSize == 2 && errorsValue.isArrayValue()) {
+            // [result, nil] or [result, errors]
```
Comment (ArtDu) [inline src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java:47]: You checked that second argument is not nil
```suggestion
            // [result, []] or [result, errors]
```

**Review by ArtDu — CHANGES_REQUESTED** [review]

File: src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java (hunk 3 above)
Comment (akudiyar) [reply src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java:47]: Fixed the comment, thanks

File: src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java (hunk 2 above)
Comment (akudiyar) [reply src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java:39]: It doesn't change the logic, although saves a few CPU cycles

File: src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java (hunk 1 above)
Comment (akudiyar) [reply src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java:46]: Let's leave it as is for verbosity and logic visibility

File: src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java (hunk 2 above)
Comment (akudiyar) [reply src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java:39]: getOrNilValue() returns NilValue in case if the index is out of range.

**Review by ArtDu — APPROVED** [review]
