### PR TITLE
Fix #82 - Last tarantool error with exception by retry

### LINKED ISSUE #82: Tarantool errors are lost if driver calls CompletableFuture.get() with timeout args
TarantoolClient.callForSingleResult() returns CompletableFuture

**get() without timeout args**: TarantoolFunctionCallException with error info from Tarantool
Caused by: TarantoolFunctionCallException: {"type":"ClientError","message":"...' ...}
        at io.tarantool.driver.api.SingleValueCallResultImpl.<init>(SingleValueCallResultImpl.java:28)
        at io.tarantool.driver.mappers.SingleValueCallResultConverter.fromValue(SingleValueCallResultConverter.java:23)
        at io.tarantool.driver.mappers.SingleValueCallResultConverter.fromValue(SingleValueCallResultConverter.java:13)
        at io.tarantool.driver.mappers.DefaultMessagePackMapper.fromValue(DefaultMessagePackMapper.java:107)
        at io.tarantool.driver.mappers.DefaultMessagePackMapper.fromValue(DefaultMessagePackMapper.java:87)
        at io.tarantool.driver.mappers.AbstractResultMapper.fromValue(AbstractResultMapper.java:27)
        at io.tarantool.driver.handlers.TarantoolResponseHandler.channelRead0(TarantoolResponseHandler.java:51)
        at io.tarantool.driver.handlers.TarantoolResponseHandler.channelRead0(TarantoolResponseHandler.java:23)

**get() with timeout args**: no error info from Tarantool
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021) ~[na:na]

### PR DESCRIPTION
**Pull request by ArtDu**
An error received from tarantool is wrapped either in `TarantoolTimeoutException` if timeout limit has been reached for retrying, or in `TarantoolAttemptsLimitException` if the retry limit has been reached.
Also tests on retrays were rewritten and supplemented.

Closes: #82

### CODE REVIEW

File: src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java [hunk 1]
```diff
@@ -104,7 +105,9 @@ public long getOperationTimeout() {
                     }
                     timeElapsed = timeElapsed + (System.nanoTime() - tStart) / 1_000_000L;
                     if (timeElapsed >= getOperationTimeout()) {
-                        ex = new TimeoutException("Operation timeout value exceeded after " + timeElapsed + " ms");
+                        if (ex instanceof TimeoutException) {
+                            ex = new TimeoutException("Operation timeout value exceeded after " + timeElapsed + " ms");
```
Comment (vrogach2020) [inline src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java:109]: As we discussed let's add new timeout exception type (for example TarantoolTimeoutException) with informative cause() method that contains last error.

File: src/test/java/io/tarantool/driver/integration/RetryingTarantoolTupleClientIT.java [hunk 2]
```diff
@@ -141,4 +143,41 @@ void testUnboundPolicyFailsAfterTimeout() throws Exception {
         assertEquals(counterVal, counter.get(),
                 "Policy continues executing request after timeout");
     }
+
+
+    /**
+     * This test covers https://github.com/tarantool/cartridge-java/issues/82
+     */
+    @Test
+    void testErrorsAfterPolicyTimeout() throws Exception {
```
Comment (vrogach2020) [inline src/test/java/io/tarantool/driver/integration/RetryingTarantoolTupleClientIT.java:152]: Let's add a same test  for AttemptRetryPolicy

**Review by vrogach2020 — CHANGES_REQUESTED** [review]

File: src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java [hunk 3]
```diff
@@ -250,6 +256,7 @@ public AttemptsBoundRetryPolicy(int attempts, long requestTimeout, long delay, T
             Assert.notNull(exceptionCheck, "Exception checking callback must not be null!");
 
             this.attempts = attempts;
+            this.limit = attempts;
```
Comment (vrogach2020) [inline src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java:259]: I don't see any sense in storing this parameter. Starting number of attemtps is known to the client of this API.

PS and of course this field should be final - it's never changed.

**Review by vrogach2020 — CHANGES_REQUESTED** [review]

File: src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java [hunk 4]
```diff
@@ -104,7 +107,9 @@ public long getOperationTimeout() {
                     }
                     timeElapsed = timeElapsed + (System.nanoTime() - tStart) / 1_000_000L;
                     if (timeElapsed >= getOperationTimeout()) {
-                        ex = new TimeoutException("Operation timeout value exceeded after " + timeElapsed + " ms");
+                        ex = new TarantoolTimeoutException(
+                                "Operation timeout value exceeded after " + timeElapsed + " ms",
```
Comment (akudiyar) [inline src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java:111]: Our custom exception can encapsulate the message and have a suitable constructor for just passing the necessary parameters. Let's move the message building into a constructor

File: src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java [hunk 5]
```diff
@@ -270,6 +277,33 @@ public boolean canRetryRequest(Throwable throwable) {
...
+                    try {
+                        return operation.get().get(getRequestTimeout(), TimeUnit.MILLISECONDS);
+                    } catch (TimeoutException | InterruptedException e) {
+                        ex = e;
+                    } catch (ExecutionException e) {
+                        ex = e.getCause();
+                    }
+                    if (attempts == 0) {
+                        ex = new TarantoolAttemptsLimitException(
+                                "Attempts limit reached: " + limit,
```
Comment (akudiyar) [inline src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java:299]: Let's move the message building into a constructor here too

File: src/test/java/io/tarantool/driver/retry/RequestRetryPolicyTest.java [hunk 6]
```diff
@@ -134,8 +135,8 @@ void testAttemptsBoundRetryPolicy_unretryableError() throws ExecutionException,
         try {
             wrappedFuture.get();
         } catch (ExecutionException e) {
-            assertTrue(e.getCause() instanceof RuntimeException);
-            assertEquals("Fail", e.getCause().getMessage());
+            assertTrue(e.getCause() instanceof TarantoolAttemptsLimitException);
+            assertEquals("Attempts limit reached: 4", e.getCause().getMessage());
```
Comment (akudiyar) [inline src/test/java/io/tarantool/driver/retry/RequestRetryPolicyTest.java:139]: The previous code checked the internal exception. Let's leave this check too

**Review by akudiyar — CHANGES_REQUESTED** [review]

File: src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java (hunk 3 above)
Comment (ArtDu) [reply src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java:259]: I think this is necessary for verbose error information

Comment (vrogach2020) [reply src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java:259]: Not critical, keep it as you wish

**Review by vrogach2020 — APPROVED** [review]

**Review by akudiyar — APPROVED** [review]
