### PR TITLE
Fix debendency conflicts

### LINKED ISSUE #297: Add dependency management

### PR DESCRIPTION
**Pull request by Elishtar**
I haven't forgotten about:
- [x] Tests
- [x] Changelog
- [ ] Documentation
- [x] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [x] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

Closes #297

### CODE REVIEW

**Review by ArtDu — CHANGES_REQUESTED** [review]
Please bump testcontainers-java-tarantool to 0.5.2 and add some words to changelog

**Comment by ArtDu** [comment]
Changelog in the following format
```
# Changelog

## [Unreleased]
- Add dependency management
- Bump snakeyaml to 1.33
- Bump junit-jupiter to 5.9.0
- Bump logback-classic to 1.2.11
```

And squash commits to the one to see the result before merging like I've done it here:
image

File: src/test/java/io/tarantool/driver/mappers/DefaultCharacterConverterTest.java [hunk 1]
```diff
@@ -15,21 +17,21 @@ class DefaultCharacterConverterTest {
 
     @Test
     void test_toValue_shouldReturnStringValue_s() {
-        DefaultCharacterConverter converter = new DefaultCharacterConverter();
```
Comment (ArtDu) [inline src/test/java/io/tarantool/driver/mappers/DefaultCharacterConverterTest.java:18]: Wtf? How did it work?

Comment (ArtDu) [reply src/test/java/io/tarantool/driver/mappers/DefaultCharacterConverterTest.java:18]: Ohhh..., It's taken from cartridge-java from cartridge-testcontainers

**Review by ArtDu — APPROVED** [review]
